apiVersion: apps/v1
kind: Deployment
metadata:
  name: readiness-exec
  labels:
    app: readiness-exec
spec:
  replicas: 3
  selector:
    matchLabels:
      app: readiness-exec
  template:
    metadata:
      labels:
        app: readiness-exec
    spec:
      containers:
      - name: readiness
        image: registry.k8s.io/busybox:latest
        args:
        - /bin/sh
        - -c
        - sleep 15; touch /tmp/healthy; sleep 600
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5
