apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80         # Port to expose the service on
    targetPort: 80 # Port on the backend pod
  clusterIP: None
