apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 80         # Port to expose the service on
    targetPort: 8080 # Port on the backend pod
  type: ClusterIP
